### ISSUE TITLE
Consider a better repository name

### ISSUE THREAD

**Issue by 0x2b3bfa0** [iterative/telemetry-python#8]
1. We're probably going to need similar repositories for languages other than Python in the short term.
2. Having iterative/iterative in the path is just... reiterative. 😉 

By the way: thanks for creating this! 😍

**Comment by mike0sv** [comment]
renaming repo and leaving pypi name, please update your remotes

**Comment by efiop** [comment]
@mike0sv Hm, not sure I follow. Why to have different names for github repo and pypi package though?

**Comment by mike0sv** [comment]
because we might have `telemetry-go` or `telemetry-js` in future

**Comment by efiop** [comment]
@mike0sv Ah, makes sense 👍 Thanks!
